export const FactoryAbi = [
	{
		name: "MarketCreated",
		inputs: [
			{ name: "marketId", type: "uint256", indexed: false },
			{ name: "marketAddr", type: "address", indexed: false },
			{ name: "creator", type: "address", indexed: false },
			{ name: "question", type: "string", indexed: false },
			{ name: "rules", type: "string", indexed: false },
			{ name: "closingTime", type: "uint256", indexed: false },
			{ name: "creatorFeePercent", type: "uint256", indexed: false },
			{ name: "timestamp", type: "uint256", indexed: false },
			{ name: "treasury", type: "address", indexed: false },
		],
		anonymous: false,
		type: "event",
	},
	{
		name: "MarketResolved",
		inputs: [
			{ name: "marketId", type: "uint256", indexed: false },
			{ name: "winningOutcome", type: "bool", indexed: false },
			{ name: "timestamp", type: "uint256", indexed: false },
		],
		anonymous: false,
		type: "event",
	},
	{
		name: "FactoryPaused",
		inputs: [
			{ name: "sender", type: "address", indexed: false },
			{ name: "paused", type: "bool", indexed: false },
			{ name: "timestamp", type: "uint256", indexed: false },
		],
		anonymous: false,
		type: "event",
	},
	{
		name: "ImplementationUpdated",
		inputs: [
			{ name: "sender", type: "address", indexed: false },
			{ name: "implementation", type: "address", indexed: false },
			{ name: "timestamp", type: "uint256", indexed: false },
		],
		anonymous: false,
		type: "event",
	},
	{
		name: "TreasuryUpdated",
		inputs: [
			{ name: "sender", type: "address", indexed: false },
			{ name: "treasury", type: "address", indexed: false },
			{ name: "timestamp", type: "uint256", indexed: false },
		],
		anonymous: false,
		type: "event",
	},
	{
		stateMutability: "nonpayable",
		type: "function",
		name: "createMarket",
		inputs: [
			{ name: "_token", type: "address" },
			{ name: "_question", type: "string" },
			{ name: "_rules", type: "string" },
			{ name: "_closingTime", type: "uint256" },
			{ name: "_creatorFeePercent", type: "uint256" },
		],
		outputs: [{ name: "", type: "address" }],
	},
	{
		stateMutability: "view",
		type: "function",
		name: "getMarket",
		inputs: [{ name: "_marketId", type: "uint256" }],
		outputs: [{ name: "", type: "address" }],
	},
	{
		stateMutability: "view",
		type: "function",
		name: "getMarketId",
		inputs: [{ name: "_marketAddr", type: "address" }],
		outputs: [{ name: "", type: "uint256" }],
	},
	{
		stateMutability: "nonpayable",
		type: "function",
		name: "triggerDefaultResolution",
		inputs: [{ name: "_marketId", type: "uint256" }],
		outputs: [],
	},
	{
		stateMutability: "nonpayable",
		type: "function",
		name: "setImplementation",
		inputs: [{ name: "_implementation", type: "address" }],
		outputs: [],
	},
	{
		stateMutability: "nonpayable",
		type: "function",
		name: "setPaused",
		inputs: [{ name: "_paused", type: "bool" }],
		outputs: [],
	},
	{
		stateMutability: "nonpayable",
		type: "function",
		name: "setTreasury",
		inputs: [{ name: "_treasury", type: "address" }],
		outputs: [],
	},
	{
		stateMutability: "view",
		type: "function",
		name: "getTimestamp",
		inputs: [],
		outputs: [{ name: "", type: "uint256" }],
	},
	{
		stateMutability: "view",
		type: "function",
		name: "getAddress",
		inputs: [],
		outputs: [{ name: "", type: "address" }],
	},
	{ stateMutability: "payable", type: "fallback" },
	{
		stateMutability: "view",
		type: "function",
		name: "treasury",
		inputs: [],
		outputs: [{ name: "", type: "address" }],
	},
	{
		stateMutability: "view",
		type: "function",
		name: "paused",
		inputs: [],
		outputs: [{ name: "", type: "bool" }],
	},
	{
		stateMutability: "view",
		type: "function",
		name: "implementation",
		inputs: [],
		outputs: [{ name: "", type: "address" }],
	},
	{
		stateMutability: "nonpayable",
		type: "constructor",
		inputs: [
			{ name: "_treasury", type: "address" },
			{ name: "_implementation", type: "address" },
		],
		outputs: [],
	},
] as const;
